services:
    recipe-management-ejs:
        image: recipe-management-ejs
        build: .
        ports:
            - "${APP_PORT:-3000}:${APP_PORT:-3000}"
        environment:
            # Inject the private key from the host system environment or .env file
            - DOTENV_PRIVATE_KEY_PRODUCTION=${DOTENV_PRIVATE_KEY_PRODUCTION}
            - NODE_ENV=production
